# -*- mode: ruby -*-
source 'https://rubygems.org'

# 'select2-foundation' itself (gem under test)
gemspec path: "../../"

gem 'rails', '~> 7.1.0'

# Asset pipeline
gem 'sprockets-rails'
gem 'sassc-rails'

gem 'jquery-rails'

gem 'foundation-rails', '~> 6.9'
gem 'select2-rails', '~> 4.0'
